### ISSUE TITLE
SASL extension no longer works

### ISSUE THREAD

**Issue by awilfox** [foxkit-us/PyIRC#15]
SASL.caps returns immediately during registration because self.mechanisms is empty.  self.mechanisms is empty because the connected event hasn't fired when CAP registration is occurring.  Yet, it needs to be done every connection because disconnect clears the state.

I can think of a few ways to fix this:

* Call ```_create_mechanisms``` in ```__init__``` as well.
* Set the priority of the connected event in SASL to lower than CapNegotiate's.
* Make the mechanism list static and use a different list for filtering ones the server doesn't support.
* Maybe something else.

What say you, @Elizafox?

**Comment by Elizafox** [comment]
See if 1ef8f5b fixes.

**Comment by awilfox** [comment]
I see what you're trying to do, but we'd need something more like 5c1a054 since it early-returns in caps before auth is even run; is this acceptable?

**Comment by awilfox** [comment]
Using 5c1a054, SASL works on Charybdis but it does not work on InspIRCd:

```
DEBUG:PyIRC.extensions.cap:Acknowledged CAP: sasl
DEBUG:PyIRC.io.socket:OUT: AUTHENTICATE PLAIN
DEBUG:PyIRC.io.socket:IN: ERROR :Closing link: (unknown@pwyll.foxkit.us) [Registration timeout]
```

I'll need to see what is different with that daemon...

**Comment by Elizafox** [comment]
Looks like SaslServ isn't getting the messages, according to off-bug banter. I'm closing this in the meantime.
